// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `frame_system_extensions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `3cb4af7e0fe5`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/vflow-node
// benchmark
// pallet
// --runtime
// /app/vflow_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// frame-system-extensions
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/vflow/src/weights/frame_system_extensions.rs
// --template
// /data/benchmark/scripts/templates/deploy-weight-template.hbs
// --base-path=/tmp/tmp.ULYpBzd15e

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weights_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `frame_system_extensions` using the zkVerify node and recommended hardware.
pub struct ZKVEvmWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> frame_system_extensions::WeightInfo for ZKVEvmWeight<T> {
    fn check_genesis() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `30`
        //  Estimated: `0`
        // Minimum execution time: 4_028_000 picoseconds.
        Weight::from_parts(4_248_000, 0)
    }
    fn check_mortality_mortal_transaction() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `68`
        //  Estimated: `0`
        // Minimum execution time: 7_704_000 picoseconds.
        Weight::from_parts(8_095_000, 0)
    }
    fn check_mortality_immortal_transaction() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `68`
        //  Estimated: `0`
        // Minimum execution time: 7_644_000 picoseconds.
        Weight::from_parts(8_085_000, 0)
    }
    fn check_non_zero_sender() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 741_000 picoseconds.
        Weight::from_parts(871_000, 0)
    }
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    fn check_nonce() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `166`
        //  Estimated: `3581`
        // Minimum execution time: 12_273_000 picoseconds.
        Weight::from_parts(12_794_000, 3581)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    fn check_spec_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 641_000 picoseconds.
        Weight::from_parts(691_000, 0)
    }
    fn check_tx_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 581_000 picoseconds.
        Weight::from_parts(661_000, 0)
    }
    fn check_weight() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_260_000 picoseconds.
        Weight::from_parts(5_550_000, 0)
    }
    fn weight_reclaim() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_436_000 picoseconds.
        Weight::from_parts(3_617_000, 0)
    }
}
