// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_collator_selection`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `99aff53bb4e5`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/vflow-node
// benchmark
// pallet
// --runtime
// /app/vflow_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-collator-selection
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/vflow/src/weights/pallet_collator_selection.rs
// --template
// /data/benchmark/scripts/templates/deploy-weight-template.hbs
// --base-path=/tmp/tmp.ULYpBzd15e

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weights_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_collator_selection` using the zkVerify node and recommended hardware.
pub struct ZKVEvmWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_collator_selection::WeightInfo for ZKVEvmWeight<T> {
    /// Storage: `Session::NextKeys` (r:10 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::Invulnerables` (r:0 w:1)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(201), added: 696, mode: `MaxEncodedLen`)
    /// The range of component `b` is `[1, 10]`.
    fn set_invulnerables(b: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `195 + b * (65 ±0)`
        //  Estimated: `1186 + b * (2540 ±0)`
        // Minimum execution time: 14_407_000 picoseconds.
        Weight::from_parts(9_038_047, 1186)
            // Standard Error: 14_443
            .saturating_add(Weight::from_parts(5_111_417, 0).saturating_mul(b.into()))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(Weight::from_parts(0, 2540).saturating_mul(b.into()))
    }
    /// Storage: `Session::NextKeys` (r:1 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:1)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(201), added: 696, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    /// The range of component `b` is `[1, 9]`.
    /// The range of component `c` is `[1, 29]`.
    fn add_invulnerable(b: u32, c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `963 + b * (20 ±0) + c * (42 ±0)`
        //  Estimated: `4393 + b * (14 ±0) + c * (44 ±0)`
        // Minimum execution time: 55_693_000 picoseconds.
        Weight::from_parts(57_358_240, 4393)
            // Standard Error: 3_108
            .saturating_add(Weight::from_parts(225_913, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_parts(0, 14).saturating_mul(b.into()))
            .saturating_add(Weight::from_parts(0, 44).saturating_mul(c.into()))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:1)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(201), added: 696, mode: `MaxEncodedLen`)
    /// The range of component `b` is `[2, 10]`.
    fn remove_invulnerable(b: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `186 + b * (20 ±0)`
        //  Estimated: `2566`
        // Minimum execution time: 12_904_000 picoseconds.
        Weight::from_parts(13_270_235, 2566)
            // Standard Error: 4_609
            .saturating_add(Weight::from_parts(264_652, 0).saturating_mul(b.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `CollatorSelection::DesiredCandidates` (r:0 w:1)
    /// Proof: `CollatorSelection::DesiredCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn set_desired_candidates() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_841_000 picoseconds.
        Weight::from_parts(6_192_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:30 w:30)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:30)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[0, 30]`.
    /// The range of component `k` is `[0, 30]`.
    fn set_candidacy_bond(c: u32, k: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0 + c * (163 ±0) + k * (118 ±0)`
        //  Estimated: `3581 + c * (872 ±29) + k * (872 ±29)`
        // Minimum execution time: 12_653_000 picoseconds.
        Weight::from_parts(12_824_000, 3581)
            // Standard Error: 265_824
            .saturating_add(Weight::from_parts(8_884_847, 0).saturating_mul(c.into()))
            // Standard Error: 265_824
            .saturating_add(Weight::from_parts(8_462_681, 0).saturating_mul(k.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
            .saturating_add(Weight::from_parts(0, 872).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 872).saturating_mul(k.into()))
    }
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[1, 30]`.
    fn update_bond(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `378 + c * (37 ±0)`
        //  Estimated: `2566`
        // Minimum execution time: 37_370_000 picoseconds.
        Weight::from_parts(39_530_682, 2566)
            // Standard Error: 5_617
            .saturating_add(Weight::from_parts(247_921, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(201), added: 696, mode: `MaxEncodedLen`)
    /// Storage: `Session::NextKeys` (r:1 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:1)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[1, 29]`.
    fn register_as_candidate(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `639 + c * (48 ±0)`
        //  Estimated: `4094 + c * (49 ±0)`
        // Minimum execution time: 51_355_000 picoseconds.
        Weight::from_parts(54_386_041, 4094)
            // Standard Error: 5_141
            .saturating_add(Weight::from_parts(327_770, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(Weight::from_parts(0, 49).saturating_mul(c.into()))
    }
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(201), added: 696, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Session::NextKeys` (r:1 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:2)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[1, 30]`.
    fn take_candidate_slot(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `726 + c * (48 ±0)`
        //  Estimated: `4186 + c * (49 ±0)`
        // Minimum execution time: 77_825_000 picoseconds.
        Weight::from_parts(81_083_241, 4186)
            // Standard Error: 6_283
            .saturating_add(Weight::from_parts(177_097, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
            .saturating_add(Weight::from_parts(0, 49).saturating_mul(c.into()))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(201), added: 696, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:1)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[1, 30]`.
    fn leave_intent(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `373 + c * (36 ±0)`
        //  Estimated: `2566`
        // Minimum execution time: 40_125_000 picoseconds.
        Weight::from_parts(42_310_867, 2566)
            // Standard Error: 4_177
            .saturating_add(Weight::from_parts(213_904, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:1)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    fn note_author() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `90`
        //  Estimated: `6172`
        // Minimum execution time: 60_162_000 picoseconds.
        Weight::from_parts(61_545_000, 6172)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(1081), added: 1576, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:30 w:0)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(201), added: 696, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::DesiredCandidates` (r:1 w:0)
    /// Proof: `CollatorSelection::DesiredCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:29 w:29)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[1, 30]`.
    /// The range of component `c` is `[1, 30]`.
    fn new_session(r: u32, c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `443 + c * (73 ±0) + r * (126 ±0)`
        //  Estimated: `3581 + c * (2507 ±0) + r * (2591 ±0)`
        // Minimum execution time: 25_638_000 picoseconds.
        Weight::from_parts(26_479_000, 3581)
            // Standard Error: 426_258
            .saturating_add(Weight::from_parts(18_724_324, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
            .saturating_add(Weight::from_parts(0, 2507).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 2591).saturating_mul(r.into()))
    }
}
