// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_xcm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `571d498a476e`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/vflow-node
// benchmark
// pallet
// --runtime
// /app/vflow_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-xcm
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/vflow/src/weights/pallet_xcm.rs
// --template
// /data/benchmark/scripts/templates/deploy-weight-template.hbs
// --base-path=/tmp/tmp.ULYpBzd15e

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weights_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_xcm` using the zkVerify node and recommended hardware.
pub struct ZKVEvmWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_xcm::WeightInfo for ZKVEvmWeight<T> {
    /// Storage: `ParachainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
    /// Proof: `ParachainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::SupportedVersion` (r:1 w:0)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::HostConfiguration` (r:1 w:0)
    /// Proof: `ParachainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::PendingUpwardMessages` (r:1 w:1)
    /// Proof: `ParachainSystem::PendingUpwardMessages` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn send() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `75`
        //  Estimated: `3540`
        // Minimum execution time: 28_613_000 picoseconds.
        Weight::from_parts(29_475_000, 3540)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
    /// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `ZKVXcm::ShouldRecordXcm` (r:1 w:0)
    /// Proof: `ZKVXcm::ShouldRecordXcm` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
    /// Proof: `ParachainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::SupportedVersion` (r:1 w:0)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::HostConfiguration` (r:1 w:0)
    /// Proof: `ParachainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    /// Storage: `ParachainSystem::PendingUpwardMessages` (r:1 w:1)
    /// Proof: `ParachainSystem::PendingUpwardMessages` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn teleport_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `144`
        //  Estimated: `3609`
        // Minimum execution time: 146_974_000 picoseconds.
        Weight::from_parts(149_629_000, 3609)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Benchmark::Override` (r:0 w:0)
    /// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn reserve_transfer_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: `Benchmark::Override` (r:0 w:0)
    /// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn transfer_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: `ZKVXcm::ShouldRecordXcm` (r:1 w:0)
    /// Proof: `ZKVXcm::ShouldRecordXcm` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn execute() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `1485`
        // Minimum execution time: 10_950_000 picoseconds.
        Weight::from_parts(11_692_000, 1485)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: `ZKVXcm::SupportedVersion` (r:0 w:1)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn force_xcm_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_616_000 picoseconds.
        Weight::from_parts(9_127_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    fn force_default_xcm_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_286_000 picoseconds.
        Weight::from_parts(3_467_000, 0)
    }
    /// Storage: `ZKVXcm::VersionNotifiers` (r:1 w:1)
    /// Proof: `ZKVXcm::VersionNotifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::QueryCounter` (r:1 w:1)
    /// Proof: `ZKVXcm::QueryCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
    /// Proof: `ParachainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::SupportedVersion` (r:1 w:0)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::HostConfiguration` (r:1 w:0)
    /// Proof: `ParachainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::PendingUpwardMessages` (r:1 w:1)
    /// Proof: `ParachainSystem::PendingUpwardMessages` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::Queries` (r:0 w:1)
    /// Proof: `ZKVXcm::Queries` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn force_subscribe_version_notify() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `75`
        //  Estimated: `3540`
        // Minimum execution time: 37_179_000 picoseconds.
        Weight::from_parts(38_221_000, 3540)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `ZKVXcm::VersionNotifiers` (r:1 w:1)
    /// Proof: `ZKVXcm::VersionNotifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
    /// Proof: `ParachainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::SupportedVersion` (r:1 w:0)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::HostConfiguration` (r:1 w:0)
    /// Proof: `ParachainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::PendingUpwardMessages` (r:1 w:1)
    /// Proof: `ParachainSystem::PendingUpwardMessages` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::Queries` (r:0 w:1)
    /// Proof: `ZKVXcm::Queries` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn force_unsubscribe_version_notify() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `165`
        //  Estimated: `3630`
        // Minimum execution time: 40_015_000 picoseconds.
        Weight::from_parts(41_087_000, 3630)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `ZKVXcm::XcmExecutionSuspended` (r:0 w:1)
    /// Proof: `ZKVXcm::XcmExecutionSuspended` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn force_suspension() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_226_000 picoseconds.
        Weight::from_parts(3_426_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ZKVXcm::SupportedVersion` (r:6 w:2)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn migrate_supported_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `22`
        //  Estimated: `15862`
        // Minimum execution time: 28_604_000 picoseconds.
        Weight::from_parts(29_565_000, 15862)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ZKVXcm::VersionNotifiers` (r:6 w:2)
    /// Proof: `ZKVXcm::VersionNotifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn migrate_version_notifiers() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `26`
        //  Estimated: `15866`
        // Minimum execution time: 28_854_000 picoseconds.
        Weight::from_parts(29_555_000, 15866)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ZKVXcm::VersionNotifyTargets` (r:7 w:0)
    /// Proof: `ZKVXcm::VersionNotifyTargets` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn already_notified_target() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `39`
        //  Estimated: `18354`
        // Minimum execution time: 33_132_000 picoseconds.
        Weight::from_parts(33_703_000, 18354)
            .saturating_add(T::DbWeight::get().reads(7_u64))
    }
    /// Storage: `ZKVXcm::VersionNotifyTargets` (r:2 w:1)
    /// Proof: `ZKVXcm::VersionNotifyTargets` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
    /// Proof: `ParachainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::SupportedVersion` (r:1 w:0)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::HostConfiguration` (r:1 w:0)
    /// Proof: `ParachainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn notify_current_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `39`
        //  Estimated: `5979`
        // Minimum execution time: 25_387_000 picoseconds.
        Weight::from_parts(26_729_000, 5979)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ZKVXcm::VersionNotifyTargets` (r:5 w:0)
    /// Proof: `ZKVXcm::VersionNotifyTargets` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn notify_target_migration_fail() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `42`
        //  Estimated: `13407`
        // Minimum execution time: 24_366_000 picoseconds.
        Weight::from_parts(24_796_000, 13407)
            .saturating_add(T::DbWeight::get().reads(5_u64))
    }
    /// Storage: `ZKVXcm::VersionNotifyTargets` (r:6 w:2)
    /// Proof: `ZKVXcm::VersionNotifyTargets` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn migrate_version_notify_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `33`
        //  Estimated: `15873`
        // Minimum execution time: 29_284_000 picoseconds.
        Weight::from_parts(29_696_000, 15873)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ZKVXcm::VersionNotifyTargets` (r:6 w:1)
    /// Proof: `ZKVXcm::VersionNotifyTargets` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
    /// Proof: `ParachainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::SupportedVersion` (r:1 w:0)
    /// Proof: `ZKVXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `ParachainSystem::HostConfiguration` (r:1 w:0)
    /// Proof: `ParachainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn migrate_and_notify_old_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `39`
        //  Estimated: `15879`
        // Minimum execution time: 41_808_000 picoseconds.
        Weight::from_parts(42_620_000, 15879)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ZKVXcm::QueryCounter` (r:1 w:1)
    /// Proof: `ZKVXcm::QueryCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::Queries` (r:0 w:1)
    /// Proof: `ZKVXcm::Queries` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn new_query() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `1485`
        // Minimum execution time: 3_967_000 picoseconds.
        Weight::from_parts(4_187_000, 1485)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ZKVXcm::Queries` (r:1 w:1)
    /// Proof: `ZKVXcm::Queries` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn take_response() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `7576`
        //  Estimated: `11041`
        // Minimum execution time: 39_304_000 picoseconds.
        Weight::from_parts(40_415_000, 11041)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ZKVXcm::ShouldRecordXcm` (r:1 w:0)
    /// Proof: `ZKVXcm::ShouldRecordXcm` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `ZKVXcm::AssetTraps` (r:1 w:1)
    /// Proof: `ZKVXcm::AssetTraps` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn claim_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `23`
        //  Estimated: `3488`
        // Minimum execution time: 48_941_000 picoseconds.
        Weight::from_parts(50_113_000, 3488)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Benchmark::Override` (r:0 w:0)
    /// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn add_authorized_alias() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: `Benchmark::Override` (r:0 w:0)
    /// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn remove_authorized_alias() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: `Benchmark::Override` (r:0 w:0)
    /// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn weigh_message() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
}
