[config]
default_to_workspace = false

[tasks.ignore-members]
workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.install-wasm]
command = "rustup"
args = ["add", "target", "wasm32-unknown-unknown"]

[tasks.check]
command = "cargo"
env = { "SKIP_WASM_BUILD" = "1" }
args = ["check", "--all-features"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.build-bench]
command = "cargo"
args = ["build", "--release", "--features", "runtime-benchmarks"]

[tasks.test-base]
command = "cargo"
env = { "SKIP_WASM_BUILD" = "1" }
args = ["test", "--release"]

[tasks.test]
dependencies = ["test-base"]
command = "cargo"
env = { "SKIP_WASM_BUILD" = "1" }
args = ["test", "--release", "--all-features"]

[tasks.test-bench]
dependencies = ["build-bench"]
command = "./target/release/vflow-node"
args = ["benchmark", "pallet", "--pallet", "*", "--extrinsic", "*", "-s", "2", "-r", "1"]

[tasks.format_inst]
[tasks.format-inst]
install_crate = {crate_name = "rustfmt", rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "--help"}

[tasks.format]
dependencies = ["format-inst"]
command = "cargo"
args = ["fmt"]

[tasks.clippy-inst]
install_crate = {crate_name = "clippy", rustup_component_name = "clippy", binary = "clippy", test_arg = "--help"}

[tasks.clippy]
dependencies = ["clippy-inst"]
command = "cargo"
env = { "SKIP_WASM_BUILD" = "1" }
args = ["clippy", "--all-targets", "--", "--deny", "warnings"]

[tasks.audit-inst]
command = "cargo"
args = ["install", "cargo-audit"]

[tasks.audit]
dependencies = ["audit-inst"]
command = "cargo"
args = ["audit"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "--workspace", "--lcov", "--output-path", "lcov.info"]

[tasks.zepter-inst]
command = "cargo"
args = ["install", "zepter", "--locked"]

[tasks.zepter-fix-check]
dependencies = ["zepter-inst"]
command = "zepter"
args = ["run", "check-fix"]

[tasks.zepter-fix-format]
dependencies = ["zepter-inst"]
command = "zepter"
args = ["run", "format-fix"]

[tasks.zepter-fix]
dependencies = ["zepter-inst"]
command = "zepter"
args = ["run", "fix"]

[tasks.zepter]
dependencies = ["zepter-fix-check", "zepter-fix-format"]

[tasks.machete]
command = "cargo"
args = ["machete"]

[tasks.dependencies-check]
dependencies = ["audit", "machete"]

[tasks.build-try-runtime]
command = "cargo"
args = ["build", "-p", "vflow-runtime", "--release", "--features", "try-runtime,volta"]

[tasks.try-runtime-inst]
command = "cargo"
args = ["install", "--git", "https://github.com/paritytech/try-runtime-cli", "--tag", "v0.10.1", "--locked"]

[tasks.try-runtime]
dependencies = ["try-runtime-inst", "build-try-runtime"]
command = "try-runtime"
args = ["--runtime", "./target/release/wbuild/vflow-runtime/vflow_runtime.compact.compressed.wasm", "on-runtime-upgrade", "--blocktime", "6",  "--disable-mbm-checks", "--disable-spec-version-check", "live", "--uri",  "wss://vflow-volta-rpc.zkverify.io"]

[tasks.ci]
dependencies = ["format", "zepter", "check", "build", "test", "test-bench", "clippy", "dependencies-check"]
