name: build-and-test

run-name: "Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cleanup space
        run:  bash ${GITHUB_WORKSPACE}/.github/scripts/clean_ci.sh

      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy, rust-src

      - name: APT update
        run: |
          sudo apt-get update -y

      - name: Install build dependencies
        run: |
          sudo apt-get install -y clang lld protobuf-compiler
          protoc --version

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.0
        with:
            cache-on-failure: true
            cache-all-crates: true

      - name: Update rust to latest version
        run: |
          rustup update

      - name: Build
        run: cargo build --release --all-features

      - name: Run tests
        run: cargo test --release --all-features
