name: Cache cleanup

run-name: Cache cleanup

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: warp-ubuntu-latest-x64-2x
    name: "Clear cache key: '${{ matrix.cache_key }}'"
    strategy:
      matrix:
        cache_key:
          - build-evm-node
          - lint-format
          - machete
          - build-runtime-benchmarks
          - unit-test
    steps:
      - name: "Deleting '${{ matrix.cache_key }}' cache key"
        uses: WarpBuilds/cache@v1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            deps/
          key: ${{ matrix.cache_key }}-${{ github.event.repository.default_branch }}
          delete-cache: true