name: global

run-name: "All CI checks"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - uses: actions/checkout@v4

      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy, rust-src

      - name: APT update
        run: |
          sudo apt-get update -y

      - name: Install build dependencies
        run: |
          sudo apt-get install -y clang lld protobuf-compiler
          protoc --version

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.0
        with:
            cache-on-failure: true
            cache-all-crates: true

      - name: Update rust to latest version
        run: |
          rustup update

      - name: Install cargo-make
        run: |
          cargo install cargo-make --locked

      - name: Run ci
        run: cargo make ci
