name: global

run-name: "All CI checks"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Rust Setup
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy, rust-src

      - name: APT update
        run: |
          sudo apt-get update -y

      - name: Install build dependencies
        run: |
          sudo apt-get install -y clang lld protobuf-compiler
          protoc --version

      - name: Rust Cache
        uses: Swatinem/rust-cache@2656b87321093db1cb55fbd73183d195214fdfd1 # v2.5.0
        with:
            cache-on-failure: true
            cache-all-crates: true

      - name: Update rust to latest version
        run: |
          rustup update

      - name: Install cargo-make
        run: |
          cargo install cargo-make --locked

      - name: Run ci
        run: cargo make ci
