name: quick-checks

run-name: "Quick Checks"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  set-image:
    # GitHub Actions allows using 'env' in a container context.
    # However, env variables don't work for forks: https://github.com/orgs/community/discussions/44322
    # This workaround sets the container image for each job using 'set-image' job output.
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      IMAGE: ${{ steps.set_image.outputs.IMAGE }}
    steps:
      - uses: actions/checkout@v4

      - id: set_image
        run: cat .github/env >> $GITHUB_OUTPUT
  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [set-image]
    container:
      image: ${{ needs.set-image.outputs.IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: Cargo fmt      
        run: cargo +nightly fmt --all -- --check
  check-rust-feature-propagation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [set-image]
    container:
      image: ${{ needs.set-image.outputs.IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: fetch deps
        run: |
          # Pull all dependencies eagerly:
          time cargo metadata --format-version=1 --locked > /dev/null
      - name: run zepter
        run: |
          zepter --version
          time zepter run check
  check-toml-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [set-image]
    container:
      image: ${{ needs.set-image.outputs.IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: check toml format
        run: |
          taplo format --check --config .config/taplo.toml
          echo "Please run `taplo format --config .config/taplo.toml` to fix any toml formatting issues"
  check-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: install python deps
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip python3
          pip3 install toml "cargo-workspace>=1.2.6"
      - name: check integrity
        run: >
          python3 .github/scripts/check-workspace.py .
