name: Tag Orchestrator

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Build/Publish Docker image
        env:
          PROD_RELEASE_BRANCH: main
          DEV_RELEASE_BRANCH: dev
          MAINTAINERS_KEYS: ${{ vars.MAINTAINERS_KEYS }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          source "${GITHUB_WORKSPACE}/ci/setup_env.sh"
          "${GITHUB_WORKSPACE}/ci/docker.sh"

  notify-slack:
    runs-on: ubuntu-latest
    needs: [ docker-job ]
    if: ${{ always() }}
    steps:
      - name: Check previous job status
        id: job_status
        run: |
          if [ "${{ needs.docker-job.result }}" == "failure" ]; then
            echo "JOB_STATUS=failed" >> $GITHUB_ENV
          else
            echo "JOB_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Notify Slack
        if: ${{ env.JOB_STATUS == 'failed' && !env.ACT }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 ALERT - zkVerify EVM Parachain CI/CD Tag Orchestrator Job Failed! 🚨"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job URL:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Job>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Pull Request:* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|View PR/Commit>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
